--------------------------------------------------------
--  File created - Tuesday-March-08-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OUTPUT_TABLE
--------------------------------------------------------

  CREATE TABLE "GAIA_INPUT"."OUTPUT_TABLE" 
   (	"MY_OUT_COL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OUTPUT_TABLE_2
--------------------------------------------------------

  CREATE TABLE "GAIA_INPUT"."OUTPUT_TABLE_2" 
   (	"ID" VARCHAR2(20 BYTE), 
	"V1" VARCHAR2(20 BYTE), 
	"V2" VARCHAR2(20 BYTE), 
	"V3" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST_CHILD_TABLE
--------------------------------------------------------

  CREATE TABLE "GAIA_INPUT"."TEST_CHILD_TABLE" 
   (	"KEY_TEST" VARCHAR2(20 BYTE), 
	"REF_COL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST_TABLE
--------------------------------------------------------

  CREATE TABLE "GAIA_INPUT"."TEST_TABLE" 
   (	"MYCOL" VARCHAR2(20 BYTE), 
	"TESTCOL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST_TABLE_2
--------------------------------------------------------

  CREATE TABLE "GAIA_INPUT"."TEST_TABLE_2" 
   (	"ID" VARCHAR2(20 BYTE), 
	"V1" VARCHAR2(20 BYTE), 
	"V2" VARCHAR2(20 BYTE), 
	"V3" VARCHAR2(20 BYTE), 
	"V4" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OUTPUT_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA_INPUT"."OUTPUT_TABLE_PK" ON "GAIA_INPUT"."OUTPUT_TABLE" ("MY_OUT_COL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OUTPUT_TABLE_2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA_INPUT"."OUTPUT_TABLE_2_PK" ON "GAIA_INPUT"."OUTPUT_TABLE_2" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEST_CHILD_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA_INPUT"."TEST_CHILD_TABLE_PK" ON "GAIA_INPUT"."TEST_CHILD_TABLE" ("KEY_TEST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEST_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA_INPUT"."TEST_TABLE_PK" ON "GAIA_INPUT"."TEST_TABLE" ("MYCOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEST_TABLE_2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA_INPUT"."TEST_TABLE_2_PK" ON "GAIA_INPUT"."TEST_TABLE_2" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table OUTPUT_TABLE
--------------------------------------------------------

  ALTER TABLE "GAIA_INPUT"."OUTPUT_TABLE" ADD CONSTRAINT "OUTPUT_TABLE_PK" PRIMARY KEY ("MY_OUT_COL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA_INPUT"."OUTPUT_TABLE" MODIFY ("MY_OUT_COL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OUTPUT_TABLE_2
--------------------------------------------------------

  ALTER TABLE "GAIA_INPUT"."OUTPUT_TABLE_2" ADD CONSTRAINT "OUTPUT_TABLE_2_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA_INPUT"."OUTPUT_TABLE_2" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST_CHILD_TABLE
--------------------------------------------------------

  ALTER TABLE "GAIA_INPUT"."TEST_CHILD_TABLE" ADD CONSTRAINT "TEST_CHILD_TABLE_PK" PRIMARY KEY ("KEY_TEST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA_INPUT"."TEST_CHILD_TABLE" MODIFY ("KEY_TEST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST_TABLE
--------------------------------------------------------

  ALTER TABLE "GAIA_INPUT"."TEST_TABLE" ADD CONSTRAINT "TEST_TABLE_PK" PRIMARY KEY ("MYCOL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA_INPUT"."TEST_TABLE" MODIFY ("MYCOL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST_TABLE_2
--------------------------------------------------------

  ALTER TABLE "GAIA_INPUT"."TEST_TABLE_2" ADD CONSTRAINT "TEST_TABLE_2_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA_INPUT"."TEST_TABLE_2" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TEST_CHILD_TABLE
--------------------------------------------------------

  ALTER TABLE "GAIA_INPUT"."TEST_CHILD_TABLE" ADD CONSTRAINT "TEST_CHILD_TABLE_TEST_TAB_FK1" FOREIGN KEY ("REF_COL")
	  REFERENCES "GAIA_INPUT"."TEST_TABLE" ("MYCOL") ENABLE;
