--------------------------------------------------------
--  File created - Tuesday-March-22-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATOMS
--------------------------------------------------------

  CREATE TABLE "GAIA"."ATOMS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"MAPPING" VARCHAR2(20 BYTE), 
	"LHS_RHS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ATOMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA"."ATOMS_PK" ON "GAIA"."ATOMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ATOMS_INDEX1
--------------------------------------------------------

  CREATE INDEX "GAIA"."ATOMS_INDEX1" ON "GAIA"."ATOMS" ("MAPPING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATOMS
--------------------------------------------------------

  ALTER TABLE "GAIA"."ATOMS" ADD CONSTRAINT "ATOMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA"."ATOMS" MODIFY ("LHS_RHS" NOT NULL ENABLE);
  ALTER TABLE "GAIA"."ATOMS" MODIFY ("MAPPING" NOT NULL ENABLE);
  ALTER TABLE "GAIA"."ATOMS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GAIA"."ATOMS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATOMS
--------------------------------------------------------

  ALTER TABLE "GAIA"."ATOMS" ADD CONSTRAINT "ATOMS_MAPPINGS_FK1" FOREIGN KEY ("MAPPING")
	  REFERENCES "GAIA"."MAPPINGS" ("ID") ON DELETE CASCADE ENABLE;
