--------------------------------------------------------
--  File created - Thursday-February-11-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KEYS_SK
--------------------------------------------------------

  CREATE TABLE "GAIA"."KEYS_SK" 
   (	"OUT" VARCHAR2(20 BYTE), 
	"FUNCTION" VARCHAR2(100 BYTE), 
	"VARIABLE_POSITION" VARCHAR2(20 BYTE), 
	"ESCHEMA" VARCHAR2(20 BYTE), 
	"ATOM_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KEYS_SK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA"."KEYS_SK_PK" ON "GAIA"."KEYS_SK" ("OUT", "ESCHEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table KEYS_SK
--------------------------------------------------------

  ALTER TABLE "GAIA"."KEYS_SK" ADD CONSTRAINT "KEYS_SK_PK" PRIMARY KEY ("OUT", "ESCHEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA"."KEYS_SK" MODIFY ("ESCHEMA" NOT NULL ENABLE);
  ALTER TABLE "GAIA"."KEYS_SK" MODIFY ("OUT" NOT NULL ENABLE);
