--------------------------------------------------------
--  File created - Thursday-July-14-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LACONIC_INDEX
--------------------------------------------------------

  CREATE TABLE "GAIA"."LACONIC_INDEX" 
   (	"MAPPING" VARCHAR2(20 BYTE), 
	"L_REL" NUMBER, 
	"R_REL" NUMBER, 
	"EXIST" NUMBER, 
	"L_JOIN" NUMBER, 
	"R_JOIN" NUMBER, 
	"L_CART" NUMBER, 
	"R_CART" NUMBER, 
	"L_JOIN_FK" NUMBER, 
	"L_CART_FK" NUMBER, 
	"R_JOIN_FK" NUMBER, 
	"R_CART_FK" NUMBER, 
	"L_JOIN_KEY" NUMBER, 
	"R_JOIN_KEY" NUMBER, 
	"VAR_COPIED" NUMBER, 
	"VAR_JOINED" NUMBER, 
	"VAR_DISJOINT" NUMBER, 
	"VAR_NORMALIZED" NUMBER, 
	"VAR_DENORMALIZED" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LACONIC_INDEX_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA"."LACONIC_INDEX_PK1" ON "GAIA"."LACONIC_INDEX" ("MAPPING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LACONIC_INDEX
--------------------------------------------------------

  ALTER TABLE "GAIA"."LACONIC_INDEX" MODIFY ("MAPPING" NOT NULL ENABLE);
  ALTER TABLE "GAIA"."LACONIC_INDEX" ADD CONSTRAINT "LACONIC_INDEX_PK1" PRIMARY KEY ("MAPPING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
