--------------------------------------------------------
--  File created - Monday-February-22-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAPPING_SETS
--------------------------------------------------------

  CREATE TABLE "GAIA"."MAPPING_SETS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"MAPPING" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MAPPING_SETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA"."MAPPING_SETS_PK" ON "GAIA"."MAPPING_SETS" ("ID", "MAPPING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MAPPING_SETS
--------------------------------------------------------

  ALTER TABLE "GAIA"."MAPPING_SETS" ADD CONSTRAINT "MAPPING_SETS_PK" PRIMARY KEY ("ID", "MAPPING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA"."MAPPING_SETS" MODIFY ("MAPPING" NOT NULL ENABLE);
  ALTER TABLE "GAIA"."MAPPING_SETS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MAPPING_SETS
--------------------------------------------------------

  ALTER TABLE "GAIA"."MAPPING_SETS" ADD CONSTRAINT "MAPPING_SETS_MAPPINGS_FK1" FOREIGN KEY ("MAPPING")
	  REFERENCES "GAIA"."MAPPINGS" ("ID") ON DELETE CASCADE ENABLE;
