--------------------------------------------------------
--  File created - Monday-February-08-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VARIABLES
--------------------------------------------------------

  CREATE TABLE "GAIA"."VARIABLES" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"MAPPING" VARCHAR2(20 BYTE), 
	"QUANTIFICATION" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VARIABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA"."VARIABLE_PK" ON "GAIA"."VARIABLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VARIABLE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAIA"."VARIABLE_UK1" ON "GAIA"."VARIABLES" ("MAPPING", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VARIABLES
--------------------------------------------------------

  ALTER TABLE "GAIA"."VARIABLES" ADD CONSTRAINT "VARIABLE_UK1" UNIQUE ("MAPPING", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA"."VARIABLES" ADD CONSTRAINT "VARIABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAIA"."VARIABLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GAIA"."VARIABLES" MODIFY ("MAPPING" NOT NULL ENABLE);
  ALTER TABLE "GAIA"."VARIABLES" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VARIABLES
--------------------------------------------------------

  ALTER TABLE "GAIA"."VARIABLES" ADD CONSTRAINT "VARIABLE_MAPPING_FK1" FOREIGN KEY ("MAPPING")
	  REFERENCES "GAIA"."MAPPINGS" ("ID") ENABLE;
